//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSach
    {
        public LoaiSach()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string GhiChu { get; set; }
        public string AnhDaiDien { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
