//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrang
    {
        public TinhTrang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.LichSuDonHangs = new HashSet<LichSuDonHang>();
        }
    
        public int ID { get; set; }
        public string TinhTrangHoaDon { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<LichSuDonHang> LichSuDonHangs { get; set; }
    }
}
