//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuDonHang
    {
        public int ID { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual TinhTrang TinhTrang1 { get; set; }
    }
}
