//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach_KhuyenMai
    {
        public int MaSach { get; set; }
        public int MaKM { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
